### ISSUE TITLE
The module's source code could not be parsed: Expected ',', got 'TValue' at https://deno.land/x/cliffy@v1.0.0-rc.3/command/types/enum.ts:6:29

### ISSUE THREAD

**Issue by tokenstakepool** [aiken-lang/fortuna#10]
Hi, I have Deno enabled. But, when I try this command:
  
  `deno task cli init`
    
I get this message:

```
   error: The module's source code could not be parsed: Expected ',', got 'TValue' at https://deno.land/x/cliffy@v1.0.0-rc.3/command/types/enum.ts:6:29
    at https://deno.land/x/cliffy@v1.0.0-rc.3/command/upgrade/upgrade_command.ts:4:26
```

**Comment by tokenstakepool** [comment]
Thank you, that solved the issue.
