### ISSUE TITLE
Continuously  getting the same error. 

### ISSUE THREAD

**Issue by gmaz98** [aiken-lang/fortuna#15]
Task cli deno run --allow-all miner/main.ts "mine"
error: Uncaught TypeError: utxos.map is not a function
    return Promise.all((utxos as any).map(async (utxo: any) => {
                                      ^
    at Kupmios.kupmiosUtxosToUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:224:39)
    at Kupmios.getUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:92:17)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Command.actionHandler (file:///Users/goncaloazevedo/Desktop/aiken/mine/fortuna/miner/main.ts:61:28)
    at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async file:///Users/goncaloazevedo/Desktop/aiken/mine/fortuna/miner/main.ts:401:1

This is happening in multiple devices all of the sudden, after everything going well. Any clue whats happening?

**Comment by nullhashpixel** [comment]
Have had the same issue since a while using kupo via demeter, maybe overload of the kupo instance.

If you have a blockfrost account, you could also use it instead.
1) add Blockfrost, to the imports in line 11 of main.ts
2) replace the 
const provider = new Kupmios(kupoUrl, ogmiosUrl);
by
const provider = new Blockfrost("https://cardano-mainnet.blockfrost.io/api/v0/", "mainnet...");

this seems to work

**Comment by jabteles** [comment]
I'm still having this error sporadically:

error: Uncaught (in promise) TypeError: utxos.map is not a function
return Promise.all((utxos as any).map(async (utxo: any) => {
^
at Kupmios.kupmiosUtxosToUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:224:39)
at Kupmios.getUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:92:17)
at eventLoopTick (ext:core/01_core.js:183:11)
at async Command.actionHandler (file:///C:/Users/xx/Downloads/fortuna-main/fortuna-main/miner/main.ts:121:28)
at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
at async file:///C:/Users/xx/Downloads/fortuna-main/fortuna-main/miner/main.ts:417:1
