### ISSUE TITLE
uncaught error: utxos.map is not a function

### ISSUE THREAD

**Issue by Jinxtaposition** [aiken-lang/fortuna#16]
Heya, getting the following error. It worked for a while, then started throwing these.
Also curious: I managed to mint one block successfully back in the beginning, but everything since has been failures to win seeking the block, like dozens. Is that normal? No idea :)

Anyway, the error:

`~/.git/fortuna$ deno task cli mine`
`Task cli deno run --allow-all miner/main.ts "mine"`
`error: Uncaught (in promise) TypeError: utxos.map is not a function`
`    return Promise.all((utxos as any).map(async (utxo: any) => {`
`                                      ^`
`    at Kupmios.kupmiosUtxosToUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:224:39)`
`    at Kupmios.getUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:92:17)`
`    at eventLoopTick (ext:core/01_core.js:183:11)`
`    at async Command.actionHandler (file:///home/mei/.git/fortuna/miner/main.ts:61:28)`
`    at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)`
`    at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)`
`    at async file:///home/mei/.git/fortuna/miner/main.ts:401:1`

I tried restarting the instance but to no avail.

**Comment by Jinxtaposition** [comment]
update: it seems to have resolved itself. Maybe a bug in kumios I guess

**Comment by jabteles** [comment]
I'm still having this error sporadically:

error: Uncaught (in promise) TypeError: utxos.map is not a function
    return Promise.all((utxos as any).map(async (utxo: any) => {
                                      ^
    at Kupmios.kupmiosUtxosToUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:224:39)
    at Kupmios.getUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:92:17)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Command.actionHandler (file:///C:/Users/xx/Downloads/fortuna-main/fortuna-main/miner/main.ts:121:28)
    at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async file:///C:/Users/xx/Downloads/fortuna-main/fortuna-main/miner/main.ts:417:1

**Comment by link78** [comment]
Hello,

I having the same error too:
eturn Promise.all((utxos as any).map(async (utxo: any) => {   
 at Kupmios.kupmiosUtxosToUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:224:39)
     
at Kupmios.getUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:92:17)    
 at eventLoopTick (ext:core/01_core.js:183:11)
 at async Command.actionHandler (file:///home/x/fortuna/miner/main.ts:105:28)  
 at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)  
 at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)  
 at async file:///home/x/fortuna/miner/main.ts:401:1

**Comment by Willburn** [comment]
Talked to a few and they all (including me) have the error now constantly.

**Comment by link78** [comment]
Me too....

**Comment by Willburn** [comment]
Is this related to Kupo perhaps?

**Comment by BrockCruess** [comment]
Same issue here, constantly.

**Comment by rvcas** [comment]
this happens when kupo is not responding correctly on demeter. Some people have started running their own instance. You can always run a private instance on demeter or host it locally.
