### ISSUE TITLE
Uncaught (in promise) TypeError: utxos.map is not a function: Keep crashing

### ISSUE THREAD

**Issue by link78** [aiken-lang/fortuna#19]
This is what I am getting

eturn Promise.all((utxos as any).map(async (utxo: any) => {   
 at Kupmios.kupmiosUtxosToUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:224:39)
     
at Kupmios.getUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:92:17)    
 at eventLoopTick (ext:core/01_core.js:183:11)
 at async Command.actionHandler (file:///home/x/fortuna/miner/main.ts:105:28)  
 at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)  
 at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)  
 at async file:///home/x/fortuna/miner/main.ts:401:1

**Comment by rvcas** [comment]
closing as it's a problem with the hosted kupo instance
