### ISSUE TITLE
unexpected EOF exception 

### ISSUE THREAD

**Issue by awenrivendell** [aiken-lang/fortuna#29]
After a few minutes, I get this error when mining:

```
error: Uncaught (in promise) TypeError: error sending request for url (https://kupo-mainnet-fortuna-api-<sanitized>.us1.demeter.run/matches/addr1wynelppvx0hdjp2tnc78pnt28veznqjecf9h3wy4edqajxsg7hwsc?unspent): connection error: unexpected end of file
    const result = await fetch(
                   ^
    at async mainFetch (ext:deno_fetch/26_fetch.js:277:12)
    at async fetch (ext:deno_fetch/26_fetch.js:501:7)
    at async Kupmios.getUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:86:20)
    at async Command.actionHandler (file:///C:/john/dev/workspace/fortuna/miner/main.ts:107:28)
    at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async file:///C:/dev/fortuna/miner/main.ts:413:1
```

``deno task cli address`` is able to show my wallet balance. Calling that unspent URL from a browser returns a well formed JSON response. Running 100% synced Kupo v2.5 and Ogmios v5.6.0. There are three UTxOs in my wallet (5, 5 and 12 ADA in each UTxO).

**Comment by awenrivendell** [comment]
I reinstalled deno and don't encounter this anymore.
