### ISSUE TITLE
Error when getting address

### ISSUE THREAD

**Issue by jaysnel** [aiken-lang/fortuna#3]
Getting this error when attempting to get address, I have all the requirements and built a wallet but can't get the actual wallet address. Running on Mac:

Task cli deno run --allow-all miner/main.ts "address"
error: Uncaught (in promise) SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
    const result = await fetch(
                   ^
    at parse (<anonymous>)
    at packageData (ext:deno_fetch/22_body.js:369:14)
    at consumeBody (ext:deno_fetch/22_body.js:246:12)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Kupmios.getUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:86:20)
    at async Command.actionHandler (file:///Users/user/Desktop/projects/cardano-aiken-fortuna/Fortuna/miner/main.ts:316:19)
    at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async file:///Users/user/Desktop/projects/cardano-aiken-fortuna/Fortuna/miner/main.ts:345:1

**Comment by deamplified** [comment]
Getting this as well. Haven't been able to find where the offending characters are located.

Fortuna + Deno on MacOS 12.5.1
Ogmios + Kupo on Demeter

**Comment by jaysnel** [comment]
Looks like the issue is being caused by line 316 of the `miner/main.ts` file.
> const addressWallet = await lucid.wallet.getUtxos();

lucid.wallet seems to work, and I can actually use that to get the address by logging it out before this line gets invoked.

I don't have enough knowledge of Lucid yet as to why the `.getUtxos()` function would be failing but definitely seems to cause some issues for some but not others. Maybe this is something with Demeter?

**Comment by deamplified** [comment]
I was able to get the address and fund the wallet. Didn't change anything on my end, just tried again after waiting.

**Comment by jaysnel** [comment]
Yeah same here, just started working this morning. Saw on twitter others are having a slight delay also. Time to mine!
