### ISSUE TITLE
SyntaxError: Unexpected token '<', "<html> <h"... is not valid JSON

### ISSUE THREAD

**Issue by the-mace** [aiken-lang/fortuna#30]
Got this after a period of mining with basic `deno task cli mine` run.

```
error: Uncaught (in promise) SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
    const result = await fetch(
                   ^
    at parse (<anonymous>)
    at packageData (ext:deno_fetch/22_body.js:369:14)
    at consumeBody (ext:deno_fetch/22_body.js:246:12)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Kupmios.getUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:86:20)
    at async Command.actionHandler (file:///Users/rob/Documents/Code/crypto/fortuna/miner/main.ts:107:28)
    at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async file:///Users/rob/Documents/Code/crypto/fortuna/miner/main.ts:413:1
```

**Comment by kochfoto** [comment]
I have been getting this error as well for the past couple of days.  Still looking for resolution.

**Comment by caike** [comment]
Likely a connection error with Kupo. Make sure you can properly connect to Kupo and Ogmios.
