### ISSUE TITLE
utxos.map is not a function

### ISSUE THREAD

**Issue by curly-knox** [aiken-lang/fortuna#31]
Get this error fairly regular like.

error: Uncaught (in promise) TypeError: utxos.map is not a function
    return Promise.all((utxos as any).map(async (utxo: any) => {
                                      ^
    at Kupmios.kupmiosUtxosToUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:224:39)
    at Kupmios.getUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:92:17)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Command.actionHandler (file:///home/curly-knox/fortuna/miner/main.ts:107:28)
    at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async file:///home/curly-knox/fortuna/miner/main.ts:413:1

**Comment by the-vj** [comment]
possibly an error related to Kupo instance not being fully initialized at the moment of invocation? e.g. to quickly after starting Kupo locally or creating a private instance on Demeter.run?
