### ISSUE TITLE
Error when creating address

### ISSUE THREAD

**Issue by AgustinBadi** [aiken-lang/fortuna#5]
When I execute `deno task cli address` i get the following error:

`Task cli deno run --allow-all miner/main.ts "address"
error: Top-level await promise never resolved
await new Command()
^
    at <anonymous> (file:///config/workspace/repo/fortuna/miner/main.ts:399:1)`

Also the vscode yells that can't find the modules that the main.ts file is importing:

I'm using demeter with Kupo 2.4.0 and  Ogmios 5.6.0

**Comment by gmaz98** [comment]
I get the following error  --> ask cli deno run --allow-all miner/main.ts "address"
error: Uncaught (in promise) TypeError: utxos.map is not a function
    return Promise.all((utxos as any).map(async (utxo: any) => {
                                      ^
    at Kupmios.kupmiosUtxosToUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:224:39)
    at Kupmios.getUtxos (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:92:17)
    at eventLoopTick (ext:core/01core.js:183:11)
    at async Command.actionHandler (file:///C:/Users/joao/desktop/mine/fortuna/miner/main.ts:370:19)
    at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
